extends:
  - standard
  - plugin:react/recommended
plugins:
  - standard
  - promise
  - react
  - jest
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true
env:
  es6: true
  node: true
  jest/globals: true
rules:
  space-before-function-paren: 0
